services:
  camouflage:
    container_name: camouflage
    entrypoint: ./entrypoint.sh
    expose:
      - 4312
      - 5555
      - 8080
      - 8081
      - 8082
      - 8443
      - 9999
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 5s
      test: wget --no-verbose --spider --tries=1 http://camouflage:8080/api/health
      timeout: 5s
    image: node:20.16.0-bookworm-slim
    labels:
      namespace: left
    ports:
      - 4312:4312
      # - 5555:5555
      - 8080:8080
      # - 8081:8081
      # - 8082:8082
      # - 8443:8443
      # - 9999:9999
    restart: "no"
    volumes:
      - ./camouflage:/camouflage
    working_dir: /camouflage
